# Generated by Django 4.2.7 on 2023-12-05 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_basic_units(apps, schema_editor):
    UnitModel = apps.get_model("inventory", "Unit")

    UNIT_LIST = [
        ("Feet", "ft"),
        ("Inches", "in"),
        ("Pounds", "lb"),
        ("Each", "ea"),
    ]

    for unit in UNIT_LIST:
        UnitModel.objects.create(id=unit[0], abbreviation=unit[1])


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name="unit")),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        help_text="leave blank if no standard abbreviation",
                        max_length=50,
                        verbose_name="standard abbreviation",
                    ),
                ),
            ],
        ),
        migrations.RunPython(add_basic_units, migrations.RunPython.noop),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="created date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="modified date")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("contact_email", models.EmailField(blank=True, max_length=254, verbose_name="contact email")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="created date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="modified date")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("contact_email", models.EmailField(max_length=254, verbose_name="contact email")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                ("vendors", models.ManyToManyField(to="inventory.vendor", verbose_name="vendor(s)")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="created date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="modified date")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="created date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="modified date")),
                ("internal_id", models.CharField(blank=True, max_length=50, verbose_name="internal identifier")),
                (
                    "vendor_id",
                    models.CharField(blank=True, max_length=50, verbose_name="vendor identifier/part number/etc."),
                ),
                ("is_sellable", models.BooleanField(verbose_name="can be sold")),
                ("is_raw_material", models.BooleanField(verbose_name="raw material")),
                (
                    "is_parent_item",
                    models.BooleanField(
                        help_text="use for items that can have multiple variations; e.g. '32 oz. Thermoflask', each color/item number will then have their own items",  # noqa: E501
                        verbose_name="parent item",
                    ),
                ),
                (
                    "in_stock_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name="amount in stock"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "in_stock_amount_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.unit", verbose_name="stock unit"
                    ),
                ),
                (
                    "parent_item",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.item",
                        verbose_name="parent item",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
