# Generated by Django 4.2.7 on 2023-12-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="internal_id",
            new_name="internal_identifier",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="vendor_id",
            new_name="vendor_identifier",
        ),
        migrations.AddField(
            model_name="item",
            name="alternate_manufacturers",
            field=models.ManyToManyField(
                related_name="alt_manufacturers", to="inventory.manufacturer", verbose_name="alternate manufacturers"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="alternate_vendors",
            field=models.ManyToManyField(
                related_name="alt_vendors", to="inventory.vendor", verbose_name="alternate vendors"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_manufacturer",
                to="inventory.manufacturer",
                verbose_name="primary manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_vendor",
                to="inventory.vendor",
                verbose_name="primary vendor",
            ),
        ),
    ]
