# Generated by Django 4.2.7 on 2023-12-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_rename_internal_id_item_internal_identifier_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["manufacturer", "is_parent_item", "name"]},
        ),
        migrations.AlterModelOptions(
            name="itemcategory",
            options={"ordering": ["name"], "verbose_name_plural": "item categories"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="item",
            name="alternate_manufacturers",
            field=models.ManyToManyField(
                null=True,
                related_name="alt_manufacturers",
                to="inventory.manufacturer",
                verbose_name="alternate manufacturers",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="alternate_vendors",
            field=models.ManyToManyField(
                null=True, related_name="alt_vendors", to="inventory.vendor", verbose_name="alternate vendors"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="in_stock_amount_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.unit", verbose_name="Stock Unit"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_vendor",
                to="inventory.vendor",
                verbose_name="Primary Vendor",
            ),
        ),
    ]
