# Generated by Django 4.2.7 on 2023-12-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_item_options_alter_itemcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="alternate_manufacturers",
            field=models.ManyToManyField(
                blank=True,
                related_name="alt_manufacturers",
                to="inventory.manufacturer",
                verbose_name="alternate manufacturers",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="alternate_vendors",
            field=models.ManyToManyField(
                blank=True, related_name="alt_vendors", to="inventory.vendor", verbose_name="alternate vendors"
            ),
        ),
    ]
