# Generated by Django 4.2.7 on 2023-12-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_item_alternate_manufacturers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="in_stock_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="amount in stock"),
        ),
    ]
