# Generated by Django 4.2.7 on 2023-12-05 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_item_in_stock_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="parent_item",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="inventory.item", verbose_name="parent item"
            ),
        ),
    ]
