# Generated by Django 4.2.7 on 2023-12-05 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_item_parent_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="parent_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.item",
                verbose_name="parent item",
            ),
        ),
    ]
