# Generated by Django 4.2.7 on 2023-12-06 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0008_item_common_color_item_item_categories_item_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="created date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="modified date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="always <= 0", max_digits=5, verbose_name="amount"
                    ),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("add", "Add"),
                            ("subtract", "Subtract"),
                            ("correct", "Correct"),
                            ("initial", "Initial"),
                        ],
                        default="subtract",
                        max_length=10,
                        verbose_name="history type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.item", verbose_name="item"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "histories",
                "ordering": ["-created_date"],
            },
        ),
    ]
