# Generated by Django 4.2.7 on 2023-12-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="amount",
            field=models.DecimalField(decimal_places=2, help_text="always >= 0", max_digits=5, verbose_name="amount"),
        ),
    ]
