exclude: "out\\.*"
default_stages: [commit]

default_language_version:
  python: python3.11

repos:
  # - repo: https://github.com/Lucas-C/pre-commit-hooks
  #   rev: v1.5.5
  #   hooks:
  #     - id: forbid-crlf
  #     - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-yaml
        args: [ --unsafe ]
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.18.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "5.0"]   # Replace with Django version
  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.15.2
      hooks:
      -   id: pyupgrade
          args: [--py36-plus,--py37-plus,--py38-plus,--py39-plus,--py310-plus,--py311-plus]
  -   repo: https://github.com/commitizen-tools/commitizen
      rev: v3.27.0
      hooks:
      -   id: commitizen
  -   repo: https://github.com/MarcoGorelli/auto-walrus
      rev: 0.3.4
      hooks:
      -   id: auto-walrus
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.6
    hooks:
      # Run the linter.
      - id: ruff
        types: [file, python]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
    - id: djlint-reformat-django
    - id: djlint-django


exclude: "(migrations|data)/.*"
