ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
default_stages:
- commit
exclude: (tests|migrations)/.*
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: detect-private-key
- repo: https://gitlab.com/bmares/check-json5
  rev: v1.0.0
  hooks:
  - id: check-json5
- repo: https://github.com/adamchainz/django-upgrade
  rev: 1.20.0
  hooks:
  - id: django-upgrade
    args: [--target-version,"5.1"]
- repo: https://github.com/iamthefij/docker-pre-commit
  rev: v3.0.1
  hooks:
  - id: docker-compose-check
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.3.3
  hooks:
  - id: python-safety-dependencies-check
    files: pyproject.toml
# - repo: https://github.com/gitleaks/gitleaks
#   rev: v8.18.2
#   hooks:
#   - id: gitleaks
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.2
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.34.1
  hooks:
  - id: djlint-reformat-django
  - id: djlint-django
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.0
  hooks:
  - id: commitizen
- repo: https://github.com/asottile/pyupgrade
  rev: v3.17.0
  hooks:
  - id: pyupgrade
    args: [--py3-plus,--py36-plus,--py37-plus,--py38-plus,--py39-plus,--py310-plus,--py311-plus]
- repo: https://github.com/python-poetry/poetry
  rev: '1.8.3'
  hooks:
  - id: poetry-check
  - id: poetry-lock
    args: [--no-update]
