version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: wooster_django_production_django
    volumes:
      - production_django_media:/app/wooster_django/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    # build:
    #   context: .
    #   dockerfile: ./compose/production/postgres/Dockerfile
    # image: wooster_django_production_postgres
    image: postgres:16-alpine
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6

  celeryworker:
    <<: *django
    image: wooster_django_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: wooster_django_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: wooster_django_production_flower
    command: /start-flower
