databases:
  - name: wooster-django-postgres
    plan: free
    databaseName: mysite
    user: mysite
    ipAllowList: []

services:
  - type: web
    plan: free
    name: wooster-django
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wooster-django-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  # - type: redis
  #   name: wooster-django-redis
  #   plan: free
  #   ipAllowList: [] # only internal connections
