# Generated by Django 4.2.7 on 2023-12-04 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentNumber",
            fields=[
                ("document", models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ("prefix", models.CharField(blank=True, max_length=10, null=True)),
                ("padding_digits", models.IntegerField(blank=True, null=True)),
                ("next_counter", models.IntegerField(default=1)),
                ("last_number", models.CharField(editable=False, max_length=50, null=True)),
                ("last_generated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="created date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="modified date")),
                ("notes", models.TextField(blank=True, max_length=255, verbose_name="notes")),
                ("project_number", models.CharField(max_length=50, unique=True, verbose_name="project number")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="customers.customer", verbose_name="customer"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
