# Generated by Django 4.2.7 on 2023-12-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_number",
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name="project number"),
        ),
    ]
