# Generated by Django 4.2.7 on 2023-12-20 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("projects", "0002_alter_project_project_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.order",
                verbose_name="Linked Order",
            ),
        ),
    ]
