# Generated by Django 4.2.7 on 2024-02-12 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DocumentNumber",
            new_name="DocumentNumbers",
        ),
    ]
