# Generated by Django 4.2.7 on 2023-12-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="item_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Item Price"),
            preserve_default=False,
        ),
    ]
