# Generated by Django 4.2.7 on 2023-12-20 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0002_orderitems_item_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name="Order Number"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.customer",
                verbose_name="Customer",
            ),
        ),
    ]
