# Generated by Django 4.2.7 on 2023-12-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_number_alter_order_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="name",
        ),
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.CharField(
                default="", editable=False, max_length=50, unique=True, verbose_name="Order Number"
            ),
            preserve_default=False,
        ),
    ]
