# Generated by Django 4.2.7 on 2023-12-20 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_history_amount"),
        ("orders", "0004_remove_order_name_alter_order_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItems",
            new_name="OrderItem",
        ),
    ]
