# Generated by Django 4.2.7 on 2023-12-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_rename_orderitems_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, verbose_name="order notes"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="rank",
            field=models.SmallIntegerField(editable=False, verbose_name="rank"),
        ),
    ]
