# Generated by Django 4.2.7 on 2024-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_notes_orderitem_notes_alter_orderitem_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentNumbers",
            fields=[
                ("document", models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ("prefix", models.CharField(blank=True, max_length=10, null=True)),
                ("padding_digits", models.IntegerField(blank=True, null=True)),
                ("next_counter", models.IntegerField(default=1)),
                ("last_number", models.CharField(editable=False, max_length=50, null=True)),
                ("last_generated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
