# Generated by Django 4.2.7 on 2024-03-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_rename_documentnumbers_documentnumber"),
        ("orders", "0010_invoice_grand_total_invoice_subtotal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.project",
                verbose_name="linked project",
            ),
        ),
    ]
