# Generated by Django 4.2.7 on 2024-03-13 10:29

from django.db import migrations, models
import wooster_django.orders.models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_invoice_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default=wooster_django.orders.models.get_default_due_date, verbose_name="due date"),
        ),
    ]
